version: '3'

services:
  nginx-proxy:
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
        - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
        - /apps/docker-articles/nginx/html:/usr/share/nginx/html
      networks:
        - ippon
      labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  node-test1:
    image: meronix/node-test1
    hostname: foo1.bar.com # foo1.bar.com / test1.romerio.site
    networks:
      - ippon
    environment:
      VIRTUAL_HOST: test1.romerio.site # foo1.bar.com / test1.romerio.site
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: test1.romerio.site
      LETSENCRYPT_EMAIL: romerio.unix@gmail.com
  node-test2:
    image: meronix/node-test2
    hostname: foo2.bar.com # foo2.bar.com / test2.romerio.site
    networks:
      - ippon
    environment:
      VIRTUAL_HOST: test2.romerio.site # foo2.bar.com / test2.romerio.site
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: test2.romerio.site
      LETSENCRYPT_EMAIL: romerio.unix@gmail.com
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html

networks:
  ippon:
    driver: bridge # Use the bridge driver
